### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by levlevin** [Galala7/homebridge-sony-sdcp#1]
For some reason, it doesn't want to work on my server. It throws the following:

[4/6/2017, 1:13:24 PM] **====================**
[4/6/2017, 1:13:24 PM] **ERROR LOADING PLUGIN homebridge-sony-sdcp:**
[4/6/2017, 1:13:24 PM] **SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-sony-sdcp/node_modules/sony-sdcp-com/index.js:1:78)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)**
[4/6/2017, 1:13:24 PM] **====================**

**Comment by levlevin** [comment]
Got it. Ubuntu defaults to an older version of Node (4.2.6), everything works on the current one (6.10.2).
