### ISSUE TITLE
ECONNRESET on any action, which then brings down homebridge

### ISSUE THREAD

**Issue by RyuKojiro** [Galala7/homebridge-sony-sdcp#7]
Config is pretty simple:
```
                {
                        "accessory": "sony-sdcp-projector",
                        "name":      "Projector",
                        "ip":        "10.0.0.128"
                },
```

After updating everything it started terminating home bridge whenever I try to turn my projector on or off through the HomeKit UI.

Here I am trying to turn it off:
```
[5/24/2023, 9:59:56 PM] [Projector] Set CurrentState: false
[5/24/2023, 9:59:56 PM] [Projector] Turning Off
[5/24/2023, 9:59:56 PM] Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[5/24/2023, 9:59:56 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by RyuKojiro** [comment]
It appears to be having trouble reading the power state, too…
```
[5/24/2023, 10:00:10 PM] [homebridge-sony-sdcp] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[5/24/2023, 10:00:16 PM] [homebridge-sony-sdcp] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[5/24/2023, 10:02:54 PM] [Projector] Set CurrentState: true
[5/24/2023, 10:02:54 PM] [Projector] Turning On
error in geting power state
[5/24/2023, 10:02:54 PM] Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[5/24/2023, 10:02:54 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by RyuKojiro** [comment]
Using `node --trace-warnings` I was able to catch this:

```
[5/24/2023, 10:24:33 PM] [Projector] Turning On
error in geting power state
(node:42339) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:42339) Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(node:42339) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by HarrHT** [comment]
After changing host to ip, power on/off of my Sony VPL-PHZ10 is working in homebridge / apple homekit, without killing hombridge:

[03/08/2025, 19:59:25] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:26] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:26] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:26] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:26] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:29] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:29] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:32] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:32] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:37] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:37] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:39] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:39] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:45] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:45] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:48] [Sony VPL-ZH10] Requested CurrentState: 0
[03/08/2025, 19:59:48] [Sony VPL-ZH10] CurrentState: 0
[03/08/2025, 19:59:52] [Sony VPL-ZH10] Set CurrentState: true
[03/08/2025, 19:59:52] [Sony VPL-ZH10] Turning On

my JSON config:
`{
    "accessory": "sony-sdcp-projector",
    "name": "Sony VPL-ZH10",
    "ip": "xxx.xxx.xxx.xxx",
    "port": "53484",
    "timeout": "30",
    "community": "SONY",
    "Debug": true
}`

What about the other functions, like INPUT?
